add_newline = false
format = "┏$username$git_branch$sudo$status\n┖$directory> "

[username]
show_always = true
style_user = "#e0def4"
style_root = "#e0def4"
format = "[\\[](bold #ea9a97)[$user]($style)[\\]](bold #ea9a97)"

[directory]
style = "#e0def4"
format = "[\\[](bold #ea9a97)[$path]($style)[\\]](bold #ea9a97)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""
style = "#e0def4"
format = "[\\[](bold #ea9a97)[$symbol$branch]($style)[\\]](bold #ea9a97)"

[git_status]
disabled = true

[sudo]
disabled = false
symbol = "⚡"
style = "#e0def4"
format = "[\\[](bold #ea9a97)[$symbol]($style)[\\]](bold #ea9a97)"

[status]
disabled = false
symbol = "x"
style = "#e0def4"
format = "[\\[](bold #ea9a97)[x$common_meaning]($style)[\\]](bold #ea9a97)"

[character]
disabled = true

[line_break]
disabled = true

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "bold #ea9a97"
